service: simple-websocket-chat-ruby

provider:
  name: aws
  region: ap-northeast-1
  runtime: ruby2.5
  websocketsApiName: SimpleChatWebSocket
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    TABLE_NAME: simple_chatconnections

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
      Resource:
        - Fn::GetAtt: [SimpleChatTable, Arn]
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'

functions:
  deafult:
    handler: default/handler.WebsocketApi.default
    events:
      - websocket:
          route: $default
  connect:
    handler: onconnect/handler.WebsocketApi.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: ondisconnect/handler.WebsocketApi.disconnect
    events:
      - websocket:
          route: $disconnect
  sendMessage:
    handler: sendmessage/handler.WebsocketApi.send_message
    events:
      - websocket:
          route: sendmessage

resources:
  Resources:
    SimpleChatTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: simple_chatconnections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
